# docker-compose.yml
version: '3.8'

services:
  redis_cv:
    image: redis:7-alpine
    container_name: redis_cv
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cv_app:
    build: .
    container_name: cv_app
    depends_on:
      redis_cv:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis_cv
      REDIS_PORT: 6379
    # you can mount your source for live code changes:
    # volumes:
    #   - ./:/app
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  node_app:
    container_name: cv_ui
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  redis_data:
